cat_config = {
    "hp": 100,
    "atk": 50,
    "speed": 1,
    "color": (255, 255, 0),
    "attack_range": 50,
    "is_aoe": True,
    "kb_limit": 5,
    "cooldown": 5000,
    "cost": 100,
    "width": 200,
    "height": 200,
    "windup_duration": 200,
    "attack_duration": 100,
    "recovery_duration": 200,
    "idle_frames": ["cat_folder/basic/attacking/basic_snail.png"],
    "move_frames": [f"cat_folder/basic/walking/basic_snail_walking{i}.png" for i in range(1, 3)],
    "windup_frames": ["cat_folder/basic/attacking/basic_snail_attcking1.png", ],
    "attack_frames": ["cat_folder/basic/attacking/basic_snail_attcking2.png",],
    "recovery_frames": [ "cat_folder/basic/attacking/basic_snail_attcking3.png"],
    "kb_frames": []
}