cat_config = {
    "hp": 500,
    "atk": 10,
    "speed": 1,
    "color": (255, 0, 255),
    "attack_range": 60,
    "is_aoe": True,
    "kb_limit": 1,
    "cooldown": 8000,
    "cost": 200,
    "width": 150,
    "height": 150,
    "windup_duration": 200,
    "attack_duration": 100,
    "recovery_duration": 200,
    "idle_frames": ["cat_folder/tank/attacking/tank.png"],
    "move_frames": ["cat_folder/tank/walking/tank-walking1.png",
                    "cat_folder/tank/walking/tank-walking2.png"],
    "windup_frames": ["cat_folder/tank/attacking/tank-attacking1.png",
                      "cat_folder/tank/attacking/tank-attacking2.png"],
    "attack_frames": ["cat_folder/tank/attacking/tank-attacking3.png"],
    "recovery_frames": ["cat_folder/tank/attacking/tank-attacking4.png"],
    "kb_frames": []
}