enemy_config = {
    "hp": 300,
    "atk": 15,
    "speed": 1,
    "color": (128, 128, 128),
    "attack_range": 60,
    "is_aoe": True,
    "kb_limit": 2,
    "is_boss": True,
    "width": 50,
    "height": 50,
    "windup_duration": 200,
    "attack_duration": 100,
    "recovery_duration": 200,
    "idle_frames": ["enemy_folder/tank/image.png"],
    "move_frames": [],
    "windup_frames": [],
    "attack_frames": [],
    "recovery_frames": [],
    "kb_frames": []
}