cat_config = {
    "hp": 300,
    "atk": 120,
    "speed": 3,
    "color": (0, 255, 255),
    "attack_range": 40,
    "is_aoe": False,
    "kb_limit": 3,
    "cooldown": 4000,
    "cost": 120,
    "width": 200,
    "height": 200,
    "windup_duration": 200,
    "attack_duration": 100,
    "recovery_duration": 200,
    "attack_interval": 2000,
    "idle_frames": ["cat_folder/speedy/walking/speedy.png"],
    "move_frames": ["cat_folder/speedy/walking/speedy.png",
                    "cat_folder/speedy/walking/speedy-walking1.png",
                    "cat_folder/speedy/walking/speedy-walking2.png",
                    "cat_folder/speedy/walking/speedy-walking1.png"],
    "windup_frames": ["cat_folder/speedy/attacking/speedy-attacking1.png",
                      "cat_folder/speedy/attacking/speedy-attacking2.png"],
    "attack_frames": ["cat_folder/speedy/attacking/speedy-attacking3.png"],
    "recovery_frames": ["cat_folder/speedy/attacking/speedy-attacking2.png",
                        "cat_folder/speedy/attacking/speedy-attacking1.png"],
    "kb_frames": ["cat_folder/speedy/walking/speedy.png"]
}